name: daily_exercise
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  firebase_core: ^2.13.0
  firebase_auth: ^4.2.9
  fluttertoast: ^8.2.1
  flutter_3d_choice_chip: ^0.1.4
  swipeable_button_view: ^0.0.2
  page_transition: ^2.0.9
  pretty_gauge: ^1.0.1
  share_plus: ^6.3.2
  flutter_ringtone_player: ^3.2.0
  carousel_slider: ^4.2.1
  #firebase_storage: ^11.0.14
  #firebase_database: ^10.0.15
  #animate_do: ^3.0.2
  #cloud_firestore: ^4.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/splash.png
    - assets/bg1.jpg
    - assets/images/beginner.jpg
    - assets/images/expert.jpg
    - assets/images/man.png
    - assets/images/woman.png
    - assets/images/core.jpg
    - assets/images/cardio2.jpg
    - assets/images/yoga.jpg
    - assets/core/abdominal.gif
    - assets/core/bicycle.gif
    - assets/core/crunch.gif
    - assets/core/dead_bug.gif
    - assets/core/female-hanging-leg-raises.gif
    - assets/core/high_plank.gif
    - assets/core/planking.gif
    - assets/core/push_ups.gif
    - assets/core/russian_twist.gif
    - assets/core/Sit-ups.gif
    - assets/core/Vsit.gif
    - assets/yoga/treepose.jpeg
    - assets/yoga/facedown.gif
    - assets/yoga/balasana.gif
    - assets/images/abs.jpeg
    - assets/images/dietgif.gif
    - assets/images/exercisesss.gif
    - assets/images/shoulder.jpeg
    - assets/images/chest.jpeg
    - assets/cardio/boxing.gif
    - assets/cardio/Burpees.gif
    - assets/cardio/jump_rope.gif
    - assets/cardio/jumping_jack.gif
    - assets/cardio/mountainclimb.gif
    - assets/cardio/squatjump.gif
    - assets/abs/Bear-Plank-Knee-Tap.gif
    - assets/abs/dumble-side-bend.gif
    - assets/abs/Glute-Bridge-March.gif
    - assets/abs/legraise.gif
    - assets/abs/plank pull.webp
    - assets/abs/reverse-crunch.gif
    - assets/upper_body/bicep.gif
    - assets/upper_body/Dumbbell-Bench-Press.gif
    - assets/upper_body/hammer-curl.gif
    - assets/upper_body/pulup.gif
    - assets/upper_body/side-lateral-raise.gif
    - assets/streatching/streach1.gif
    - assets/streatching/streach2.gif
    - assets/streatching/streach3.gif
    - assets/streatching/streach4.gif
    - assets/acrobatic/acrobalance.gif
    - assets/acrobatic/Aerial.gif
    - assets/acrobatic/cart-wheel.gif
    - assets/acrobatic/hand-stand.gif
    - assets/hands/Dips.gif
    - assets/hands/Dumbbell-Front.gif
    - assets/hands/Dumbbell-Pullover.webp
    - assets/hands/Incline-Dumbbell.gif
    - assets/hands/Pinch.gif
    - assets/shoulder/arnold-press.gif
    - assets/shoulder/barbell.gif
    - assets/shoulder/dumbbellreversefly.gif
    - assets/shoulder/face-pull.gif
    - assets/shoulder/overhead.gif
    - assets/shoulder/pike.gif
    - assets/shoulder/Rear-delt-fly.gif
    - assets/images/normaldiet.png
    - assets/images/Weight-Loss.jpg
    - assets/images/Underweight.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
